"""Pre-boot context generation for cache-optimised agent sessions.

Concatenates boot-sequence governance files and governance artifact
listings into a single static markdown file.  Outputs to two locations:

- ``.agents/spec-driver-boot.md`` — for Claude Code (symlinked into .claude/rules/)
- ``.pi/APPEND_SYSTEM.md`` — for pi (auto-discovered, appended to system prompt)

Both outputs are identical. Content-diffing avoids unnecessary writes
that would bust token caches.

See: DE-091, DR-091, DE-093, mem.fact.claude-code.context-loading
"""

from __future__ import annotations

import subprocess
from pathlib import Path

from .config import load_workflow_config
from .paths import SPEC_DRIVER_DIR

# Output locations (relative to repo root)
PREBOOT_OUTPUT_DIR = Path(".agents")
PREBOOT_OUTPUT_FILE = "spec-driver-boot.md"

# pi-native output: .pi/APPEND_SYSTEM.md (auto-discovered by pi)
PI_OUTPUT_DIR = Path(".pi")
PI_OUTPUT_FILE = "APPEND_SYSTEM.md"

# Boot-sequence files in canonical order.
# Each tuple: (section_heading, path_relative_to_repo_root)
BOOT_SEQUENCE: list[tuple[str, str]] = [
  ("Dogma", f"{SPEC_DRIVER_DIR}/about/dogma.md"),
  ("Execution Environment", f"{SPEC_DRIVER_DIR}/agents/exec.md"),
  ("Glossary", f"{SPEC_DRIVER_DIR}/agents/glossary.md"),
  ("Workflow", f"{SPEC_DRIVER_DIR}/agents/workflow.md"),
  ("Skill Routing", f"{SPEC_DRIVER_DIR}/agents/routing.md"),
  ("Policy & Governance", f"{SPEC_DRIVER_DIR}/agents/policy.md"),
  ("Memory", f"{SPEC_DRIVER_DIR}/agents/memory.md"),
  ("Project Doctrine", f"{SPEC_DRIVER_DIR}/hooks/doctrine.md"),
]

# Governance listings to append after the policy section.
# Each tuple: (section_heading, list_command_args)
GOVERNANCE_LISTINGS: list[tuple[str, list[str]]] = [
  ("Accepted ADRs", ["list", "adrs", "-s", "accepted", "--format=tsv"]),
  ("Required Policies", ["list", "policies", "-s", "required", "--format=tsv"]),
  ("Required Standards", ["list", "standards", "-s", "required", "--format=tsv"]),
]

GENERATED_HEADER = "<!-- Generated by spec-driver admin preboot — do not edit -->"


def _resolve_exec_command(repo_root: Path) -> list[str]:
  """Resolve the spec-driver exec command from workflow.toml."""
  config = load_workflow_config(repo_root)
  exec_str = config.get("tool", {}).get("exec", "uv run spec-driver")
  return exec_str.split()


def _read_boot_file(repo_root: Path, rel_path: str) -> str:
  """Read a boot-sequence file, returning its content or a warning."""
  path = repo_root / rel_path
  if not path.is_file():
    return f"<!-- missing: {rel_path} -->"
  return path.read_text(encoding="utf-8").strip()


def _run_listing(exec_cmd: list[str], args: list[str]) -> str:
  """Run a governance listing command, returning TSV output or a warning."""
  try:
    result = subprocess.run(
      [*exec_cmd, *args],
      capture_output=True,
      text=True,
      timeout=30,
      check=False,
    )
    if result.returncode == 0:
      return result.stdout.strip()
    return f"<!-- listing failed: {' '.join(args)} -->"
  except (subprocess.TimeoutExpired, FileNotFoundError):
    return f"<!-- listing unavailable: {' '.join(args)} -->"


def generate_preboot_content(repo_root: Path) -> str:
  """Generate the full preboot context file content.

  Reads boot-sequence files and governance listings, concatenates
  them into a single markdown document per DR-091 §8 format.

  Args:
    repo_root: Repository root path.

  Returns:
    Complete preboot markdown content.
  """
  exec_cmd = _resolve_exec_command(repo_root)
  sections: list[str] = [GENERATED_HEADER, "", "# Spec-Driver Boot Context"]

  # Governance listings are inserted after the policy section
  policy_heading = "Policy & Governance"

  for heading, rel_path in BOOT_SEQUENCE:
    content = _read_boot_file(repo_root, rel_path)
    sections.append("")
    sections.append(f"## {heading}")
    sections.append("")
    sections.append(content)

    if heading == policy_heading:
      for listing_heading, listing_args in GOVERNANCE_LISTINGS:
        listing = _run_listing(exec_cmd, listing_args)
        sections.append("")
        sections.append(f"## {listing_heading}")
        sections.append("")
        sections.append(listing)

  # Ensure trailing newline
  sections.append("")
  return "\n".join(sections)


def _write_if_changed(path: Path, content: str) -> bool:
  """Write content to path only if it differs. Returns True if written."""
  path.parent.mkdir(parents=True, exist_ok=True)
  if path.is_file():
    existing = path.read_text(encoding="utf-8")
    if existing == content:
      return False
  path.write_text(content, encoding="utf-8")
  return True


def write_preboot_file(repo_root: Path) -> Path:
  """Generate and write preboot context files.

  Writes to:
    - ``.agents/spec-driver-boot.md`` — for Claude Code
      (via symlink into .claude/rules/)
    - ``.pi/APPEND_SYSTEM.md`` — for pi (auto-discovered, appended to system prompt)

  Both files receive identical content. Only writes if content has changed
  (avoids unnecessary file touches that would bust token caches).

  Args:
    repo_root: Repository root path.

  Returns:
    Path to the primary output file (.agents/spec-driver-boot.md).
  """
  content = generate_preboot_content(repo_root)

  # Primary output (Claude Code)
  primary_path = repo_root / PREBOOT_OUTPUT_DIR / PREBOOT_OUTPUT_FILE
  _write_if_changed(primary_path, content)

  # pi-native output (auto-discovered as APPEND_SYSTEM.md)
  pi_path = repo_root / PI_OUTPUT_DIR / PI_OUTPUT_FILE
  _write_if_changed(pi_path, content)

  return primary_path
