"""Pre-boot context generation for cache-optimised agent sessions.

Concatenates boot-sequence governance files and governance artifact
listings into a single static markdown file.  When loaded into
``.claude/rules/`` (via symlink), this file lands in Claude Code's
cacheable prefix — eliminating per-session tool-call overhead.

See: DE-091, DR-091, mem.fact.claude-code.context-loading
"""

from __future__ import annotations

import subprocess
from pathlib import Path

from .config import load_workflow_config
from .paths import SPEC_DRIVER_DIR

# Output location (relative to repo root)
PREBOOT_OUTPUT_DIR = Path(".agents")
PREBOOT_OUTPUT_FILE = "spec-driver-boot.md"

# Boot-sequence files in canonical order.
# Each tuple: (section_heading, path_relative_to_repo_root)
BOOT_SEQUENCE: list[tuple[str, str]] = [
  ("Dogma", f"{SPEC_DRIVER_DIR}/about/dogma.md"),
  ("Execution Environment", f"{SPEC_DRIVER_DIR}/agents/exec.md"),
  ("Glossary", f"{SPEC_DRIVER_DIR}/agents/glossary.md"),
  ("Workflow", f"{SPEC_DRIVER_DIR}/agents/workflow.md"),
  ("Policy & Governance", f"{SPEC_DRIVER_DIR}/agents/policy.md"),
  ("Memory", f"{SPEC_DRIVER_DIR}/agents/memory.md"),
  ("Project Doctrine", f"{SPEC_DRIVER_DIR}/hooks/doctrine.md"),
]

# Governance listings to append after the policy section.
# Each tuple: (section_heading, list_command_args)
GOVERNANCE_LISTINGS: list[tuple[str, list[str]]] = [
  ("Accepted ADRs", ["list", "adrs", "-s", "accepted", "--format=tsv"]),
  ("Required Policies", ["list", "policies", "-s", "required", "--format=tsv"]),
  ("Required Standards", ["list", "standards", "-s", "required", "--format=tsv"]),
]

GENERATED_HEADER = "<!-- Generated by spec-driver admin preboot — do not edit -->"


def _resolve_exec_command(repo_root: Path) -> list[str]:
  """Resolve the spec-driver exec command from workflow.toml."""
  config = load_workflow_config(repo_root)
  exec_str = config.get("tool", {}).get("exec", "uv run spec-driver")
  return exec_str.split()


def _read_boot_file(repo_root: Path, rel_path: str) -> str:
  """Read a boot-sequence file, returning its content or a warning."""
  path = repo_root / rel_path
  if not path.is_file():
    return f"<!-- missing: {rel_path} -->"
  return path.read_text(encoding="utf-8").strip()


def _run_listing(exec_cmd: list[str], args: list[str]) -> str:
  """Run a governance listing command, returning TSV output or a warning."""
  try:
    result = subprocess.run(
      [*exec_cmd, *args],
      capture_output=True,
      text=True,
      timeout=30,
      check=False,
    )
    if result.returncode == 0:
      return result.stdout.strip()
    return f"<!-- listing failed: {' '.join(args)} -->"
  except (subprocess.TimeoutExpired, FileNotFoundError):
    return f"<!-- listing unavailable: {' '.join(args)} -->"


def generate_preboot_content(repo_root: Path) -> str:
  """Generate the full preboot context file content.

  Reads boot-sequence files and governance listings, concatenates
  them into a single markdown document per DR-091 §8 format.

  Args:
    repo_root: Repository root path.

  Returns:
    Complete preboot markdown content.
  """
  exec_cmd = _resolve_exec_command(repo_root)
  sections: list[str] = [GENERATED_HEADER, "", "# Spec-Driver Boot Context"]

  # Governance listings are inserted after the policy section
  policy_heading = "Policy & Governance"

  for heading, rel_path in BOOT_SEQUENCE:
    content = _read_boot_file(repo_root, rel_path)
    sections.append("")
    sections.append(f"## {heading}")
    sections.append("")
    sections.append(content)

    if heading == policy_heading:
      for listing_heading, listing_args in GOVERNANCE_LISTINGS:
        listing = _run_listing(exec_cmd, listing_args)
        sections.append("")
        sections.append(f"## {listing_heading}")
        sections.append("")
        sections.append(listing)

  # Ensure trailing newline
  sections.append("")
  return "\n".join(sections)


def write_preboot_file(repo_root: Path) -> Path:
  """Generate and write the preboot context file.

  Writes to ``.agents/spec-driver-boot.md`` under the repo root.
  Only writes if content has changed (avoids unnecessary file touches).

  Args:
    repo_root: Repository root path.

  Returns:
    Path to the written file.
  """
  output_dir = repo_root / PREBOOT_OUTPUT_DIR
  output_dir.mkdir(parents=True, exist_ok=True)
  output_path = output_dir / PREBOOT_OUTPUT_FILE

  content = generate_preboot_content(repo_root)

  # Only write if changed (avoids unnecessary mtime updates)
  if output_path.is_file():
    existing = output_path.read_text(encoding="utf-8")
    if existing == content:
      return output_path

  output_path.write_text(content, encoding="utf-8")
  return output_path
