classes: {
  important: {
    style: {
      fill: "#ff00ff"
      font-color: "#ffffff"
    }
  }

  process: {
    shape: parallelogram
    style: {
      fill: "#abefff"
      font: mono
      font-size: 16
    }
  }

  artifact: {
    shape: page
    style: {
      fill: "#ffefab"
    }
  }

  critpath: {
    style: {
      stroke-width: 4
    }
  }
  emits: {
    label: defines
    style: {
      stroke: "#777777"
    }
  }
  updates: {
    label: updates
    style: {
      # stroke: "#777777"
    }
  }
  informs: {
    label: informs
    style: {
      stroke-dash: 4
      stroke: "#7799cc"
    }
  }
}
# #
# #
vars: {
  d2-legend: {
    d: {
      label: "the important part"
      class: important
      style: {
        fill: "#ff00ff"
        font-color: "#ffffff"
      }
    }
  }
}

capture.class: process
scope.class: process
design: {
  class: process
  style: {
    fill: "#ff00ff"
    font-color: "#ffffff"
  }
}
plan.class: process
execute.class: process
verify.class: process

delta: {
  style.fill: "#ffdecd"
  style.stroke: "#cc7755"
  class: artifact

  design_revision: {
    class: important
    shape: page
    label: "design\nrevision"
  }

  implementation_plan: {
    class: artifact
    label: "implementation\nplan"
    # phases: {
    #   style.multiple: true
    #   class: artifact
    # }
  }
}

research: {
  label: "research | truth"
  product_spec: {
    class: artifact
    label: "product spec"
    style.fill: "#eeefff"
    requirements: {
      style.multiple: true
      class: artifact
    }
  }

  tech_spec: {
    class: artifact
    label: "tech spec"
    style.fill: "#feefef"
    requirements: {
      style.multiple: true
      class: artifact
    }
  }

  contracts: {
    class: artifact
    label: "generated\ncontracts"
    style: {
      fill: "#eeeeee"
      multiple: true
    }
  }
}
research -> design: {class: informs}
research -> plan: {class: informs}

backlog: {
  ideas: {
    style.multiple: true
    class: artifact
  }
  issues: {
    style.multiple: true
    class: artifact
  }
  problems: {
    style.multiple: true
    class: artifact
  }
  risks: {
    style.multiple: true
    class: artifact
  }
}

#
# workflow
#

capture -> scope -> design -> plan -> execute -> verify: {class: critpath}

capture -> backlog: {class: emits}
backlog -> scope: {class: informs}
scope -> delta: {class: emits}
design -> delta.design_revision: {class: emits}
plan -> delta.implementation_plan: {class: emits}
execute -> code: {class: updates}

code: {
  label: codebase
  shape: hexagon
}

code -> research.contracts: {
  class: emits
  label: emits
}

delta -> verify: {class: informs}
code -> verify: {class: informs}
verify -> research: {class: updates}
research.contracts -> verify: {class: informs}
